name: Build Distributable

on:
  push:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "eng/docs/**"
      - "scripts"
  pull_request:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "eng/docs/**"
      - "scripts"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Lint with flake8
        run: |
          flake8 src
      - name: Build
        run: |
          ./eng/build_pyz.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pnasmedia.pyz
          path: build/pnasmedia.pyz
